/* DO NOT EDIT, file generated by nestjs-i18n */

/* eslint-disable */
/* prettier-ignore */
import type { Path } from "nestjs-i18n";
/* prettier-ignore */
export type I18nTranslations = {
    "common": {
        "months": {
            "january": string;
            "february": string;
            "march": string;
            "april": string;
            "may": string;
            "june": string;
            "july": string;
            "august": string;
            "september": string;
            "october": string;
            "november": string;
            "december": string;
        };
    };
};
/* prettier-ignore */
export type I18nPath = Path<I18nTranslations>;
